name: MultiDimensionsHierarchies Deployment

on:
  push:
    tags:
      - 0.*
      - 1.*

env:
  configuration: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: NuGet Restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Unit Tests
        run: dotnet test --configuration=Release --verbosity=minimal --no-build
        working-directory: src

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Pack
        run: dotnet pack -p:PackageVersion=${{ steps.tagName.outputs.tag }} --configuration=Release --verbosity=minimal --no-build
        working-directory: src

      - name: Push
        run: dotnet nuget push **/MultiDimensionsHierarchies/nupkg/*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate